### ISSUE TITLE
Cannot use configured template directory for setup task

### ISSUE THREAD

**Issue by DarrenInwood** [silverstripe/silverstripe-realme#10]
The setup task template directory cannot use a configured directory other than the default.

To replicate, copy the realme templates/simplesaml-configuration folder into mysite/templates, thenset in yaml -
RealMeSetupTask:
  template_config_dir: 'mysite/templates/simplesaml-configuration'

Running the setup task uses the realme module template directory, where it should use the configured directory.

**Comment by madmatt** [comment]
Fixed by #11 which is merged now.
