### ISSUE TITLE
RealMe has rebranded

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-realme#105]
New branding need to be applied. 

![image](https://github.com/silverstripe/silverstripe-realme/assets/1168676/5588a115-93dc-45aa-8f28-cb14a0d08bda)

## Acceptance criteria
- Module UI uses the latest RealMe branding.
- Fix is targeted at a new minors of the Realme module.
- Fix is available for CMS 5 and CMS 4

## Deployment
- After the PR is merged, a beta should be tagged. Max will then ask the person who requested this change to test the beta.
- After the beta has been tested, a new minor release will be tagged for CMS 4 - and _THEN_ we can merge up to CMS 5.

## Notes
- Realme has a style guide and icons which can be downloaded [from this page](https://developers.realme.govt.nz/how-to-integrate/application-design-and-branding-guide/realme-new-page-elements/)
  - There are apparently ["other design considerations for login"](https://developers.realme.govt.nz/how-to-integrate/application-design-and-branding-guide/other-design-considerations-for-login/) and ["some design considerations for assert"](https://developers.realme.govt.nz/how-to-integrate/application-design-and-branding-guide/other-design-considerations-for-assert/)
- [Private service desk ticket](https://servicedesk.silverstripe.cloud/a/tickets/110422?) (Silverstripe staff only)

## PRs
After merging, re-assign to the dev who did the work to resolve any issues for merging up to CMS 5
- https://github.com/silverstripe/silverstripe-realme/pull/113

**Comment by maxime-rainville** [comment]
Some random questions:
- Do we want to fix this in CMS 4 as well?
- Do we need to ship this in a minor release?

**Comment by maxime-rainville** [comment]
Following discussion, we've decidide to target the fix at a new minor of CMS 4. This somewhat breaks our major release policy, but this is a somewhat unusual situation because a third party has forced this on us.

We do not consider this a precedent for how we will do other minor releases for other CMS 4 modules.

**Comment by GuySartorelli** [comment]
I've migrated the single css file to multiple scss files, mirroring what was done in CMS 5. This should make the merge up process easier.

On merge up to `5.0`, basically discard all changes, then delete the `client/src/styles` and `client/images` directories and grab the content of those directories from the `4` branch, and run `yarn build`

**Comment by emteknetnz** [comment]
@GuySartorelli have merged linked PR, you'll need to merge-up and do another PR for the CMS 5 webpack

**Comment by GuySartorelli** [comment]
@maxime-rainville Assigned to you to organise the people who wanted this to test it as discussed. The beta is tagged as [4.5.0-beta1](https://github.com/silverstripe/silverstripe-realme/releases/tag/4.5.0-beta1)

**Comment by maxime-rainville** [comment]
Just followed up with the Service Desk customer and ask them to deploy to a test environment and let us know if it works OK.

**Comment by GuySartorelli** [comment]
We didn't get any feedback so we're just gonna release it. Tagged as [4.5.0](https://github.com/silverstripe/silverstripe-realme/releases/tag/4.5.0) and [5.1.0](https://github.com/silverstripe/silverstripe-realme/releases/tag/5.1.0)
