### ISSUE TITLE
Generate temp folders if they don't exist

### ISSUE THREAD

**Issue by madmatt** [silverstripe/silverstripe-realme#16]
If the default `/tmp/simplesaml` directory doesn't exist, SimpleSAMLphp just freezes up and fails to do anything. We should ensure the directory is created before handing control over (or use a different library)

**Comment by dhensby** [comment]
Submit an upstream PR?

**Comment by madmatt** [comment]
Closing this as way out-of-date, the newer versions will use a different lib anyway.
