### ISSUE TITLE
Signing into RealMe loses session data in SilverStripe

### ISSUE THREAD

**Issue by torleif** [silverstripe/silverstripe-realme#165]
### Module version(s) affected

5.3.2

### Description

The default Session variable in SilverStripe 5 has the SameSite=Lax setting enabled. 

**SameSite Cookie Policy**: The `SameSite=Lax` setting allows cookies to be sent with cross-site **GET** requests but not **POST** requests. Since the RealMe return uses a `POST `request, the session cookie is not sent back, causing the session to reset.

### How to reproduce

1. Create a session variable in your SilverStripe instance. 
2. Sign in to RealMe
3. Your session will be reset

### Possible Solution

Change the default cookie settings, or enable a way to pass through additional data

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

**Comment by GuySartorelli** [comment]
When you say "Your session will be reset" - what are the actual effects of that? What problems does this cause, specifically?

**Comment by GuySartorelli** [comment]
Closing as I cannot reproduce and additional information was not provided when requested.

**Comment by torleif** [comment]
Appologies - when i say my session was reset - all session varables set $_Session[...] etc get erased

**Comment by NightJar** [comment]
I'm not sure there's a way around this within the module. Because the session cookie is absent in the request (per SameSite setting) a new session cookie is created. This then overrides whatever was set before the AuthN at the IdP.
Without a session existing, there is no way to persist state between requests, thus no one could log in.

Other than explicitly loosening the cookie attributes before redirection to RealMe (which seems counter-intuitive), I don't have enough experience to know if there's some standard way to deal with the problem.

**Comment by NightJar** [comment]
Ah, duh.
That's what `RelayState` is for, of course.

It needs to be checked properly, of course (ensure it's a site URL before using it)
https://github.com/silverstripe/silverstripe-saml/commit/798d5036604ecafada69fa1bfe65e516bfc1f683

@torleif are you able to inspect your SAML response to see if the request var is set?
It should be falling back to it (and is checked for `validSiteURL`).
https://github.com/silverstripe/silverstripe-realme/blob/214710edeb3d0aa18229970515bf2a77c9c05f75/src/RealMeService.php#L654-L657

**Comment by torleif** [comment]
@NightJar Hey NightJar, yes, the RelayState works as expected. It's how we're getting around the issue of losing our session data: storing an encrypted ID inside a GET variable on the return URL in RelayState. However, it is a bit janky—all our session variables have to be stored in a data object before being reused.

We recently started implementing Apple Sign In, and they've got a restriction where you have to whitelist your return URLs, including any GET variables you add.

This caused us to rethink how we're doing it, and these YAML settings will allow you to preserve the session data:

```
SilverStripe\Control\Session:
  timeout: 0
  cookie_domain: '.op.ac.nz'
  cookie_secure: true
  cookie_httponly: true
  cookie_samesite: 'None'
```

it does involve taking the cookie_samesite security from 'Lax' to 'None', however.

**Comment by NightJar** [comment]
Hi @torleif 

Ah, so am I correct to assume that the session data set before logging in is both somehow important to be carried over, and more general than simply where to redirect the user to?

This does complicate matters a little. I think generally unauthenticated data is seen as somewhat unimportant - though I guess if one has dissmissed pop-ups or alert banners, etc. then that would also be wiped.

The only way I could see to get around that would be to store the details in relation to the `samlp:AuthnRequest[ID]` attribute - this comes back to match as `samlp:Response[InResponseTo]` - that way you won't need GET vars, which will allow for allow-listing RelayState URLs.

[`RealMeService::getAuth`](https://github.com/silverstripe/silverstripe-realme/blob/214710edeb3d0aa18229970515bf2a77c9c05f75/src/RealMeService.php#L907) should give you access to these details. I'm not sure if there's a hook in the appropriate place to do extra work with it though - perhaps a PR could be in order if not (or making this issue more specific and asking for it to be reopened).

You would need to re-set the session data on both Authn success _and failure_, in order for it to be 'seemless' to the user.
While also being careful not to give out sessions to e.g. replay attacks, etc. Probably deleting your stored data after it is restored would be effective enough.

**Comment by torleif** [comment]
Yes, that's correct. Imagine a situation where someone has, say, a shopping cart, authenticates into RealMe, and then loses their items in the cart after logging in.

One avenue I tried exploring but couldn’t figure out was an issue caused by [silverstripe/silverstripe-hybridsessions](https://github.com/silverstripe/silverstripe-hybridsessions). I noticed it reinitializes the session on POST if no session cookie is set.

In theory, you could avoid setting any cookies after a POST request, retain the authentication information, and rely on the browser to send the previous session variable after a redirect.

**Comment by NightJar** [comment]
Interesting @torleif, and a good example thanks (shopping cart).
Your proposed solution seems to be quite similar to the issues described in [an issue on the SAML module](https://github.com/silverstripe/silverstripe-saml/issues/45) - where conflicting session IDs seemingly battle each other.

I'm not sure how that solution would work though - a session is needed in order to persist the authenticated state. If a redirect happens after authentication which conforms to SameSite requirements, then it would be that the user information is stored nowhere... unless a secondary session cookie (with a different name) is used. Seems to be getting rather complex though :/

**Comment by NightJar** [comment]
🤔Thinking about this a little more (as I believe it will soon impact me)

Setting a session variable with a different name in `ACS` then redirecting to another _controlled_ endpoint such as `realme/login` (i.e. not the homepage, etc. - names made up to demonstrate point)

The `acs` -> `login` URL will be an internal/SameSite redirect which will/should then include the original session cookie, and can then consume and delete the secondary `acs` session, before redirecting to the desired back url (either `RelayState` or `RequestHandler::getBackUrl`, etc.)

This is just a theoretical approach at this point, essentially turning the `acs` action into a two-step process.

I think it should work... As does your database storage of session data beforehand. I'm just considering ways to avoid the [double-session issue](https://github.com/silverstripe/silverstripe-saml/issues/45) described in the SAML module.
