### ISSUE TITLE
[v2] Remove need for custom onelogin/php-saml fork

### ISSUE THREAD

**Issue by madmatt** [silverstripe/silverstripe-realme#17]
### Overview
Currently, the fork is required because of [this annoying XMLDSig issue](https://github.com/madmatt/php-saml/commit/a77a7a3c49cd6d4fa4652a57a5febb9aa3f9abea). Once we can get a workable solution merged back into the base module, we can remove this.

Once done, we also need to update the installation instructions (docs/en/installation.md) to remove the custom repository note.

### Versions affected
This change needs to be made on both the 2.x and 3.x line for SS3 and SS4 compatibility.

### Notes
This should be tested using the MTS environment

**Comment by sminnee** [comment]
FYI we'll probably need to make this work for CWP 1.9 as well...

**Comment by brynwhyman** [comment]
Copying from elsewhere: @madmatt 

> We can definitely test #17 again now - the issue is that logon and assert endpoints were throwing different XML signatures - one that was valid and one that wasn't. We've also found that the signature has changed recently, meaning we needed to re-fix that code too, so I'd rather remove it and get rid of the fork if possible.

**Comment by NightJar** [comment]
https://github.com/silverstripe/silverstripe-realme/pull/45 has updated the `onelogin` dependency, and _not_ re-applied the patch in the fork referenced above in this issue.

However testing has only been carried out on MTS, I've heard from @ScopeyNZ that the issue only manifests on ITE or Prod. There is an environment set up, seems like once running a few simple test will soon tell.

**Comment by NightJar** [comment]
Thanks to @leapfrognz for helping out, we managed to test this in an ITE environment and receive an error - which then went away after applying the `madmatt` fork's fix atop the 3.2.1 upstream branch.

It appears this is still required.

**Comment by madmatt** [comment]
Well that's stink :(

If we have time, some investigation would be awesome to try and figure out what is causing the issue (especially to confirm it's not the namespace messing that onelogin/php-saml is doing itself just before my added code).

**Comment by NightJar** [comment]
OK, so I had a chat with @indygriffiths about #38 - his experience was the exact _opposite_ of what we encountered, although he was using `assert`, where the test here has been for `login`.
So this is worthy of more testing, but for now is resolved as "still required" until proof otherwise :)

**Comment by NightJar** [comment]
Well, I was just testing the `login` service in `ITE` - Everything worked as expected, hooray!
Then I realised that I did **not** have the fork listed in my composer.json - and on double check, it was not installed.

SO now the project appears to work without the fork - yay!

I think the outcome here might be to list it as a note in the `README` stating something along the lines of:

"If you find a problem with dSig matching, please try with the `madmatt` fork which _may_ solve the issue."

**Comment by flashbackzoo** [comment]
I've run into a problem with matching signatures using the @madmatt fork. This is using CWP v2.4.0 and a RealMe-via-WSO2 integration.

See https://github.com/onelogin/php-saml/issues/396

**Comment by NightJar** [comment]
Neat, thanks for weighing in @flashbackzoo - seems to be that it's no longer needed. I'm curious as to what configuration lead to the fork requirement in the project that seemed to need it... but otherwise it seems to be a necessity of the past. I'll make a quick note in a troubleshooting section of the readme, then hopefully that'll be enough.

The less custom configuration required to make this module go the better, so this really is the ideal out come (that it works without the madmatt fork).
