### ISSUE TITLE
Check and update module for SS4 compatibility where necessary

### ISSUE THREAD

**Issue by rupachup** [silverstripe/silverstripe-realme#21]
**User Story**
As a CMS user I can use the RealMe login offering to login to my website (frontend, or backend). As with other modules, the new SilverStripe RealMe module will require some re-configuration when developers upgrade from CWP 1.0 to CWP 2.0, so an upgrade path will be provided as part of this effort.

**Acceptance Criteria**

- works in 4 as it did in 3

**Sub Tasks**

- [ ] 

- [ ] 

Dependancy, but not included within this estimate: Requires infrastructure setup from DIA

**Comment by charles-ritchie** [comment]
Any idea if this will be implemented in time for CWP recipe 2 release?

**Comment by robbieaverill** [comment]
We're hoping to have it ready in time

**Comment by NightJar** [comment]
PR in (and merged) at https://github.com/silverstripe/addons.silverstripe.org/pull/204
