### ISSUE TITLE
Assertion response contains mis-matched tag

### ISSUE THREAD

**Issue by indygriffiths** [silverstripe/silverstripe-realme#38]
When using the `assert` integration type, a change in https://github.com/madmatt/php-saml/commit/4636d95be2d45ee1d9c3ebce46386fc93686c7a5 is causing responses from MTS to fail due to a mismatched XML tag (`saml:NameID`)

```
<saml:Attribute Name="urn:nzl:govt:ict:stds:authn:attribute:igovt:IVS:FIT" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified">
    <saml:AttributeValue xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">
        <saml:NameID Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent" NameQualifier="https://identity.dev.i.govt.nz:443/ivs/ivs-idp">
            XXXXXXXXXXXXXXXX
        </saml2:NameID>
    </saml:AttributeValue>
</saml:Attribute>
```

Not too sure the logic behind the change was given the commit mentions ITE, but as it stands you can't successfully use assertion with MTS with this change in place.

**Comment by ScopeyNZ** [comment]
I think this logic was introduced by that custom fork to work around a bug in RealMe. Perhaps they've fixed their bug (probably long ago) and are no longer accepting the behaviour that their bug required?

This will almost certainly be fixed by #17 .

**Comment by madmatt** [comment]
Hrm, that's annoying. The original issue was that ITE/Production would *sign* different XML to what it *actually sent you* (at least, that was my conclusion after spending way too long testing it).

The only reason I noticed it was that the XML I received looked like this:
`<saml:NameID xmlns:saml2="namespace declaration">`. The XML DSig was failing to validate (it doesn't say why, so you're left to guess), and when I "fixed" that by manually changing the ns of the tag to be `<saml2:NameID` it worked fine.

As a useful reference for when you inevitably end up banging your head against a wall with this for hours like I have, Peter Guttman's take on 'Why XML Security is broken' is an alternating amazing and then tear-jerking read: https://www.cs.auckland.ac.nz/~pgut001/pubs/xmlsec.txt.

If I get some time and the courage, I'll try and re-review whether all of this fork nonsense is still necessary. I really hope it isn't, but I have a sneaking suspicion it will be.

**Comment by NightJar** [comment]
I'm waiting on an assert ITE environment, but signs are pointing to no longer needing the php-saml fork. This is good news!

**Comment by madmatt** [comment]
Closing now as the fork is no longer required.
