### ISSUE TITLE
login_member_after_authentication doesn't work

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-realme#46]
https://github.com/silverstripe/silverstripe-realme/blob/3cdbc9d0fe373d14c0081f59bf933db0a95e3b6d/src/Authenticator/LoginHandler.php#L118

RequestAuthenticationHandler is an empty class with no handlers assigned to it.
AuthenticationHandler is an interface (which would cause an instantiation error), but is also the name of a defined service, a pre-configured instance of RequestAuthenticationHandler with handlers assigned.

ie. change`RequestAuthenticationHandler::class` to `AuthenticationHandler::class` and things should work again.

**Comment by brynwhyman** [comment]
Hey @NightJar it looks like this was resolved with #47, can you please confirm?

**Comment by NightJar** [comment]
Oh rude, the auto-close didn't trigger :(
![image](https://user-images.githubusercontent.com/778003/67722406-e9902d80-fa3d-11e9-8ee9-1675424fe065.png)


Yeah, this is done @brynwhyman :)
