### ISSUE TITLE
New module releases

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-realme#50]
Following the completion of #24 new versions need to be released for sites to adopt for PHP7.2 compatibility.

Raising as a separate issue to cover any conversation that may be required before this happens.

Releases will be required for both the SS3 and SS4 versions of the module.

**Comment by brynwhyman** [comment]
Would be nice to see how we could support getting this change in too https://github.com/silverstripe/silverstripe-realme/pull/40

**Comment by lukereative** [comment]
https://github.com/silverstripe/silverstripe-realme/pull/53

**Comment by dnsl48** [comment]
The version `4.0` of the module has been released with support for `Silverstripe CMS 4.x`.
Request for support of PHP 7.2+ for `CMS 3.x` is captured in https://github.com/silverstripe/silverstripe-realme/issues/56
