### ISSUE TITLE
Support for Silverstripe CMS 3 with PHP >=7.2

### ISSUE THREAD

**Issue by dnsl48** [silverstripe/silverstripe-realme#56]
Support for CMS 4 was implemented in https://github.com/silverstripe/silverstripe-realme/pull/55

We may need to ensure the older version of this module works for CMS 3 with PHP>=7.2 (obviously with 7.1 too)

**Comment by brynwhyman** [comment]
For a little more context, the following PR has already been merged into the `3` line: https://github.com/silverstripe/silverstripe-realme/pull/53. There were early reports from @lukereative that testing with this went well.

At this stage, Silverstripe is looking for community contributions to aid in testing the CMS version 3 line of this module. If you're looking for some support, feel free to post here 😃

**Comment by madmatt** [comment]
I made some quick and dirty tests for this and it seems to work okay still for both logon and assert. I think we can close this issue now.
