### ISSUE TITLE
Config value sp_entity_ids[mts] not set

### ISSUE THREAD

**Issue by epi-liang** [silverstripe/silverstripe-realme#58]
Not sure whether silverstripe-realme only works on CWP. 
I would like to have a test on non-CWP (version 4.4) and I do have the sp_entity_ids in realme.yml, however I got the following message when executing the command "vendor/bin/sake dev/tasks/RealMeSetupTask forEnv=mts"

```
Running Task RealMe Setup Task

Config value sp_entity_ids[mts] not set
```

**Comment by dnsl48** [comment]
Hi!
No, it does not require CWP for work. We list all the requirements in the `composer.json` of the module. However, it requires quite a bit of configuration to work properly. We have a dedicated documentation file for that - https://github.com/silverstripe/silverstripe-realme/blob/4/docs/en/configuration.md

In your particular case, it looks like maybe your `realme.yml` wasn't picked up by the framework or you forgot to `?flush` after you've changed that file.

That doesn't seem to be a bug to me, so I'll close this issue, but feel free to reopen if that doesn't work after you make sure it's configured properly, following the docs.
