### ISSUE TITLE
Broken build - phpcs + asserting two strings are equal

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-realme#67]
https://travis-ci.com/github/silverstripe/silverstripe-realme/jobs/490008359
phpcs

https://travis-ci.com/github/silverstripe/silverstripe-realme/jobs/490008360
1) SilverStripe\RealMe\Tests\RealMeServiceTest::testGetAuth
Failed asserting that two strings are identical.

### PRs:
- [x] https://github.com/silverstripe/silverstripe-realme/pull/68

**Comment by maxime-rainville** [comment]
Fixed by https://github.com/silverstripe/silverstripe-realme/pull/68
